[package]
name = "ntcp"
version = "0.1.0"
authors = ["awski <adam.wolanski@protonmail.com>"]
edition = "2018"

# Workaround to due "Segfault compilation libc"
[profile.release]
codegen-units = 1

[dependencies]
tun-tap = "0.1.2"
etherparse = "0.9.0"